### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by oikomi** [zhangpeihao/gortmp#11]
I want to use [Sourcegraph code search and code review](https://sourcegraph.com) with gortmp. A project maintainer needs to enable it to set up a webhook so the code is up-to-date there.

Could you please enable gortmp on @Sourcegraph by going to https://sourcegraph.com/github.com/zhangpeihao/gortmp and clicking on Settings? (It should only take 15 seconds.)

Thank you!

**Comment by zhangpeihao** [comment]
Enabled
