### ISSUE TITLE
can not real push data to wowza

### ISSUE THREAD

**Issue by wangziUSTC** [zhangpeihao/gortmp#12]
I have already created a stream to wowza, but use OutboundStream.PublishVideoData or OutboundStream.PublishAudioData can not real push data to wowza. Stream status is active but Bytes In is 0. There is no err return.

What can I do for check this error.

**Comment by wangziUSTC** [comment]
还是用中文说吧。 我尝试使用这个库进行rtmp流的推送，我下载了wowza做测试server。建立流的过程中并没有出错，看wowza的统计页面也能看到有新的stream。中间会收到connection succeeded的command。在OnStreamCreated的回调中调用Publish（“streamName”， “live”）后，再调用OutboundStream的PublishVideoData和PublishAudioData，在wowza看来，bytes in 一直是0，中间也不会报错。如果用ffmpeg来推rtmp流的话，是没有问题的。

**Comment by zhangpeihao** [comment]
wowza没有用过。
如果你有公网测试服务器，把信息发到我的gmail邮箱，我可以测试看看。

**Comment by vincentqiu** [comment]
什么时候能支持wowza 服务器 ？

**Comment by zhangpeihao** [comment]
加我QQ：7123862

2016-08-30 11:57 GMT+08:00 vincent <notifications@github.com>:

**Comment by zhangpeihao** [comment]
已经支持了
