### ISSUE TITLE
Send RPC command to server

### ISSUE THREAD

**Issue by anykao** [zhangpeihao/gortmp#14]
I cant input zhongwen, so I will ask in English.
I want to  send command to FMS. 
But I have noticed that the outboundconnection.Call is unimplemented.

Can you give me some advice.
By the way , thank you  for this library. It help me a lot.

The real request looks like this.

![image](https://cloud.githubusercontent.com/assets/1076537/7434019/c577b484-f071-11e4-80b6-336a55e6b6d0.png)

**Comment by norwack** [comment]
https://github.com/zhangpeihao/gortmp/blob/master/outboundconn.go#L49

**Comment by zhangpeihao** [comment]
I will append the 'Call' method in to 'OutboundConnHandler' interface in the week.
:)

**Comment by zhangpeihao** [comment]
I appended the "Call method" into both OutboundStream and OutboundConn interfaces. In your case, you should use the Call method of OutboundConn.

I only tested it in AMF0 format,  if you have the environment of AMF3,  I will be happy to test it.

**Comment by anykao** [comment]
Thank you for your help. 
I have check your code. And find it really helpful.
