### ISSUE TITLE
publish 时， 碰到 音频和视频解码步骤不一致， 只听到音频， 看不到视频

### ISSUE THREAD

**Issue by vincentqiu** [zhangpeihao/gortmp#25]
header.Timestamp: 5408, now: 1472553720757848290
diff1: 5408
== publishdata: 8 5408
diff1: 5440
== publishdata: 8 5440
diff1: 5472
== publishdata: 8 5472
diff1: 5504
== publishdata: 8 5504
header.Timestamp: 5536, now: 1472553720886429117
diff1: 5536
== publishdata: 8 5536
== diff1
diff1: 0
== publishdata: 9 0
diff1: 5568
== publishdata: 8 5568
diff1: 5600
== publishdata: 8 5600
diff1: 5632
== publishdata: 8 5632
header.Timestamp: 5664, now: 1472553721016424239
Audio size: 284381 bytes; Vedio size: 1713772 bytes
diff1: 68
== publishdata: 9 68
diff1: 5664
== publishdata: 8 5664
diff1: 5696
== publishdata: 8 5696
diff1: 5728
== publishdata: 8 5728
diff1: 168
== publishdata: 9 168
diff1: 5760
== publishdata: 8 5760

**Comment by vincentqiu** [comment]
看着时间已经不一致了 。

**Comment by zhangpeihao** [comment]
加我QQ：7123862

2016-08-30 18:53 GMT+08:00 vincent <notifications@github.com>:

**Comment by zhangpeihao** [comment]
FLV文件的时间戳不对
