### ISSUE TITLE
vlc卡顿

### ISSUE THREAD

**Issue by ije** [zhangpeihao/gortmp#29]
按照demo/server, 建立的rtmp服务器用vlc播放卡顿！
尝试把 `if diff1 > diff2+100 {` 改为 `if diff1 > diff2 {` 有所改善， 但依旧卡的不行

**Comment by ije** [comment]
用手机的mxplayer似乎没问题

**Comment by zhangpeihao** [comment]
加QQ群：320720829

**Comment by ije** [comment]
谢谢
