### ISSUE TITLE
rtmp receive bytes are always 0 from a live stream

### ISSUE THREAD

**Issue by pavan4** [zhangpeihao/gortmp#33]
```
rtmp:rtmp://188.138.17.8:1935/albuk/albuk.stream stream:stream_name flv:./video_dump
to dial
@@@@@@@@@@@@@status: 1, err: <nil>
obConn: &{url:rtmp://188.138.17.8:1935/albuk/albuk.stream rtmpURL:{protocol:rtmp host:188.138.17.8 port:1935 app:albuk instanceName:albuk.stream} status:1 err:<nil> handler:0x7760b0 conn:0xc42000a900 transactions:map[] streams:map[]}
obConn.URL(): rtmp://188.138.17.8:1935/albuk/albuk.stream
to connect
@@@@@@@@@@@@@status: 3, err: <nil>
ReceviedCommand: &{IsFlex:false Name:_result TransactionID:1 Objects:[map[capabilities:31 mode:1 fmsVer:FMS/3,5,7,7009] map[objectEncoding:0 level:status code:NetConnection.Connect.Success description:Connection succeeded. data:map[version:3,5,7,7009] clientid:9.77161e+06]]}
@@@@@@@@@@@@@status: 5, err: <nil>
Stream created: 1
ReceviedCommand: &{IsFlex:false Name:_result TransactionID:2 Objects:[<nil> 1]}
Audio size: 0 bytes; Vedio size: 0 bytes
Audio size: 0 bytes; Vedio size: 0 bytes
Audio size: 0 bytes; Vedio size: 0 bytes
```

Am I running or setting it up wrong?

**Comment by zhangpeihao** [comment]
./player -URL rtmp://188.138.17.8:1935/albuk -Stream albuk.stream -DumpFLV ./demo.flv

============
to dial
@@@@@@@@@@@@@status: 1, err: <nil>
obConn: &{url:rtmp://188.138.17.8:1935/albuk rtmpURL:{protocol:rtmp host:188.138.17.8 port:1935 app:albuk instanceName:} status:1 err:<nil> handler:0x1368a78 conn:0xc420068300 transactions:map[] streams:map[]}
obConn.URL(): rtmp://188.138.17.8:1935/albuk
to connect
@@@@@@@@@@@@@status: 3, err: <nil>
ReceviedCommand: &{IsFlex:false Name:_result TransactionID:1 Objects:[map[fmsVer:FMS/3,5,7,7009 capabilities:31 mode:1] map[level:status code:NetConnection.Connect.Success description:Connection succeeded. data:map[version:3,5,7,7009] clientid:3.7718465e+07 objectEncoding:0]]}
@@@@@@@@@@@@@status: 5, err: <nil>
Stream created: 1
ReceviedCommand: &{IsFlex:false Name:_result TransactionID:2 Objects:[<nil> 1]}
Audio size: 0 bytes; Vedio size: 37446 bytes
Audio size: 0 bytes; Vedio size: 237859 bytes
Audio size: 6022 bytes; Vedio size: 304138 bytes
Audio size: 19114 bytes; Vedio size: 470531 bytes
Audio size: 32347 bytes; Vedio size: 621389 bytes
